name: Update Progress

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run fetchData.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node fetchData.js

      - name: Commit & push progress.json
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add data/progress.json
          git commit -m "update progress [auto]" || echo "no changes"
          git push
